apiVersion: v2
name: subimage-outpost
description: Deploy SubImage Outpost with Tailscale in restrictive Kubernetes environments
type: application
version: 1.0.2
appVersion: "1.0.2"
home: https://subimage.io
sources:
  - https://github.com/subimagesec/helm-charts
keywords:
  - tailscale
  - proxy
  - outpost
  - security
maintainers:
  - name: SubImage
    url: https://subimage.io
