{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # Pod Security Standards labels
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurity.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurity.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurity.warn }}
{{- end }}
