apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "subimage-outpost.fullname" .) }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "subimage-outpost.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
